### PR TITLE
Add env vars VNCGROUP, VNCGID, VNCUMASK and make container restartable

### PR DESCRIPTION
**Pull request by CWempe**
I added two environment variables to let the user define custom group name and group-id for non-root user.

And in my case I need the file permissions written to some volumes to be writable by `group` so I added an option to set `umask`.

I also delete some temp files from vnc server, because the vnc server was not reachable after `docker restart  ubuntu-desktop`.

### CODE REVIEW

**Comment by CWempe** [comment]
I was not able to use the clipboard across my host (Win10, TigerVNC) and vnc server.

I fixed this, too.

**Comment by Fullaxx** [comment]
@CWempe just excellent, thanks for this! I meant to ask you about the group and GID and I forgot.

**Comment by Fullaxx** [comment]
I make a few small tweaks, I believe all the intended functionality remains intact, let me know if anything doesn't work right

**Comment by CWempe** [comment]
I just realized setting umask did not solve my problem.
It only affects file creation via shell, but it does not work with other applications.

I am not sure I can solve this by myself via docker.
The application needs an option to set the default permissions, I guess.

But I think it does not hurt to have this feature in this container. 😄

**Comment by Fullaxx** [comment]
I wonder if that's because the BiglyBT is being launched from xstartup (and not a shell that you started manually)? Try quitting the application and launching it manually from an xterm window? Let me know if you see any different behavior?

**Comment by CWempe** [comment]
You are right.
Starting BiglyBT from terminal workes.

Let's see if I can work with this information. :)

**Comment by CWempe** [comment]
Fixed.
https://github.com/Fullaxx/ubuntu-desktop/pull/2

Thanks for the hint.

**Pull request merged**
